# Generated by Django 4.2.11 on 2024-05-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuserprofile',
            name='phone',
            field=models.IntegerField(default=123, max_length=12),
            preserve_default=False,
        ),
    ]
