# Generated by Django 4.2.11 on 2024-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_createuserprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserprofile',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
