# Generated by Django 4.2.11 on 2024-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='demo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default=1234),
            preserve_default=False,
        ),
    ]
