# Generated by Django 4.2.11 on 2024-05-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_details',
            field=models.IntegerField(blank=True, max_length=12),
        ),
    ]
