# Generated by Django 4.2.11 on 2024-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('HTML/CSS', 'HTML/CSS')], max_length=100),
        ),
    ]
