# Generated by Django 4.2.11 on 2024-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Graphic Design', 'Graphic Design'), ('Others', 'Others')], max_length=100),
        ),
    ]
